language: go
go:
- 1.13

jobs:
  include:
    - stage: style
      script:
        - make style
    - stage: unit tests
      script:
        - make test
        - ./check_coverage.sh
      after_success:
        - bash <(curl -s https://codecov.io/bash)
    - stage: REST API tests
      script:
        - make rest_api_tests

stages:
  - style
  - unit tests
  - REST API tests
