[broker]
address = "localhost:9092"
topic = "ccx.ocp.results"
group = "aggregator"
enabled = true

[logging]

[metrics]
enabled = true

[processing]
org_whitelist = "org_whitelist.csv"

[rules]
content_auto_update = true
content_update_cron = "0 0 * * *"
content_update_script = "update_insights_rules_content.sh"

[server]
address = ":8080"
api_prefix = "/api/v1/"
api_spec_file = "openapi.json"
debug = true

[storage]
db_driver = "sqlite3"
sqlite_datasource = "./aggregator.db"
pg_username = "user"
pg_password = "password"
pg_host = "localhost"
pg_port = 5472
pg_db_name = "aggregator"
pg_params = ""

