[broker]
address = "localhost:9092"
topic = "ccx.ocp.results"
group = "aggregator"
enabled = true

[server]
address = ":8080"
api_prefix = "/api/v1/"

[processing]
org_whitelist = "./org_whitelist.csv"

[metrics]
enabled = true

[logging]

[storage]
driver = "sqlite3"
datasource = "./aggregator.db"
