version: "3"
services:
  db:
    ports:
      - 55432:5432
    image: registry.access.redhat.com/rhscl/postgresql-10-rhel7
    environment:
      - POSTGRESQL_USER=user
      - POSTGRESQL_PASSWORD=password
      - POSTGRESQL_ADMIN_PASSWORD=admin
      - POSTGRESQL_DATABASE=aggregator
  zookeeper:
    image: confluentinc/cp-zookeeper
    environment:
      - ZOOKEEPER_CLIENT_PORT=32181
      - ZOOKEEPER_SERVER_ID=1
      - ZOOKEEPER_LOG4J_ROOT_LOGLEVEL=ERROR
      - ZOOKEEPER_TOOLS_LOG4J_LOGLEVEL=ERROR
  kafka:
    image: confluentinc/cp-kafka
    ports:
      - 29092:29092
    depends_on:
      - zookeeper
    environment:
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:29092
      - KAFKA_BROKER_ID=1
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:32181
  minio:
    image: minio/minio
    command: 
      - server
      - /data
    volumes:
      - ../minio/data/:/data:Z
      - ../minio/config:/root/.minio:Z
    ports:
      - 9000:9000
    environment:
      - MINIO_ACCESS_KEY=BQA2GEXO711FVBVXDWKM
      - MINIO_SECRET_KEY=uvgz3LCwWM3e400cDkQIH/y1Y4xgU4iV91CwFSPC
  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint:
      - /bin/sh
      - -c
      - "sleep 5;
      /usr/bin/mc config host add myminio http://minio:9000 BQA2GEXO711FVBVXDWKM uvgz3LCwWM3e400cDkQIH/y1Y4xgU4iV91CwFSPC;
      /usr/bin/mc mb myminio/insights-upload-perma;
      /usr/bin/mc mb myminio/insights-upload-rejected;
      /usr/bin/mc policy download myminio/insights-upload-perma;
      /usr/bin/mc policy download myminio/insights-upload-rejected;
      exit 0;
      "
  ingress:
    # you can build the image from these sources
    # https://github.com/RedHatInsights/insights-ingress-go
    image: localhost/ingress:latest 
    ports:
      - 3000:3000
    environment:
      - AWS_ACCESS_KEY_ID=BQA2GEXO711FVBVXDWKM
      - AWS_SECRET_ACCESS_KEY=uvgz3LCwWM3e400cDkQIH/y1Y4xgU4iV91CwFSPC
      - AWS_REGION=us-east-1
      - INGRESS_STAGEBUCKET=insights-upload-perma
      - INGRESS_REJECTBUCKET=insights-upload-rejected
      - INGRESS_VALIDTOPICS=testareno,platform.upload.testareno
      - OPENSHIFT_BUILD_COMMIT=woopwoop
      - INGRESS_MINIODEV=true
      - INGRESS_MINIOACCESSKEY=BQA2GEXO711FVBVXDWKM
      - INGRESS_MINIOSECRETKEY=uvgz3LCwWM3e400cDkQIH/y1Y4xgU4iV91CwFSPC
      - INGRESS_MINIOENDPOINT=minio:9000
    depends_on:
      - kafka
      - minio
