title: Insights Results Aggregator
description: Aggregator service for Openshist insights results
baseurl: ""
url: "https://redhatinsights.github.io/insights-results-aggregator"

heading_anchors: true

aux_links:
  "Github repository":
    - "https://github.com/RedHatInsights/insights-results-aggregator"

footer_content: "Copyright &copy; 2020 Red Hat.</a>"

# Build settings
markdown: kramdown
remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-remote-theme

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/
